import Head from "next/head";
import { Fragment } from "react";
import Hero from "../components/home-page/hero";
import FeaturedPosts from '../components/home-page/featured-posts'
import DUMMY_DATA from '../dummy_data.json'

function Home() {
  return (
    <div>
      <Head>
        <title>My post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Fragment>
        <Hero />
        <FeaturedPosts posts={DUMMY_DATA} />
      </Fragment>
    </div>
  );
}

export default Home;
